### ISSUE TITLE
Notification does not work

### ISSUE THREAD

**Issue by rocketraman** [jlewallen/jenkins-hipchat-plugin#19]
I see this in my jenkin logs:

```
Mar 20, 2012 10:14:21 AM jenkins.plugins.hipchat.StandardHipChatService publish
INFO: Posting: Jenkins to 40365: my-project-build - #81 Success after 8 min 3 sec (<a href='https://my.domain.com/jenkins/job/my-project-build/81/'>Open</a>) green
```

however I never get the notification in Hipchat. I have tried both the room ID as well as room name.

How can I debug this further?

PS This used to work fine. Not sure when it stopped working. I updated to the latest jenkins and hipchat plugin to see if that would fix it, but it didn't.

**Comment by darrinholst** [comment]
You can setup some more verbose logging within jenkins to try and track down the problem. Instructions to do that are [here](https://wiki.jenkins-ci.org/display/JENKINS/Logging)

Something like http://cl.ly/062x0N2J0y0o3j3W3F2t should get you plenty of details on what's going on from the http side.

**Comment by rocketraman** [comment]
Thanks, I will try it (this tip might be useful info for a wiki page).

**Comment by rocketraman** [comment]
Here is the log:

https://gist.github.com/2140247

There are no errors, and yet I still do not see the notification. I have verified the API key and room #.

**Comment by darrinholst** [comment]
Here is the last part of the log from a successful notification from my system:

https://gist.github.com/2158006

Hipchat is returning an "Authorization required" in your case. I'd try running it locally and looking at the messages with something like [Charles](http://www.charlesproxy.com/)

**Comment by rocketraman** [comment]
I will throw a packet capture on it to see what the traffic between jenkins and hipchat is, but shouldn't the hipchat plugin be a little better at reporting API call failures?

**Comment by darrinholst** [comment]
sure, I don't think a patch for that will be rejected ;)

**Comment by rocketraman** [comment]
Once I figure out what is wrong I may very well have a patch for you... :)

**Comment by rocketraman** [comment]
Looks like this was an API token failure -- I was sure I had checked it but the gremlins got in there somehow.

I added pull request #20 to add a WARN level logging if the HipChat API call does not contain "sent". This will help debug this sort of issue.

**Comment by ghost** [comment]
I came across this issue while debugging notification failures between Jenkins and HipChat; adding my own fix for future travelers.

Make sure you use an `Admin` API token, and **not** a `Notification` type. I knocked on this for two days before trying the admin type, and things started right back up.

**Comment by etheriau** [comment]
As this came up when I was troubleshooting, note that the Admin/Notification are both V1 API tokens which are only creatable via an Admin account.
