### ISSUE TITLE
Show Build Parameters

### ISSUE THREAD

**Issue by AshtonKem** [jlewallen/jenkins-hipchat-plugin#37]
We use parameterized jobs to deploy services, and we are notified about their start/finish via Hipchat. Knowing what environment is being deployed to in Hipchat would make our life much easier.

**Comment by aaronmaxlevy** [comment]
+1

**Comment by mtwalsh** [comment]
+1

**Comment by aaronmaxlevy** [comment]
One thing I am not sure of is why this plugin does not utilize the Jenkins Instant Messaging Plugin like the IRC plugin, as well as the Jabber plugin for example. That plugin has this feature built-in.
