### ISSUE TITLE
Release to Jenkins-ci.org

### ISSUE THREAD

**Issue by pjboudrx** [jlewallen/jenkins-hipchat-plugin#8]
I don't have a Java dev environment, and I'm used to adding plugins via the Jenkins management UI. 
Would you be willing to follow the steps at https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org so this plugin can be added to a CI as easily as other plugins can?

Or has this been done, and I'm missing it?

BTW, thanks for building this plugin; I'd love to help get this published, but it will be a while before I have the opportunity.
Thanks!
-Patrick

**Comment by cbos** [comment]
I did not know that this plugin existed till a colleague pointed me out. 
If it would have been released on Jenkins-ci.org I would have known it.  

By releasing it to Jenkins-ci.org it will give exposure to the Jenkins community as well.
There is an RSS feed of plugin updates, and wiki updates on plugin changes. 
Multiple users of Jenkins keep and eye on updates as well.

By seeing an update of an new plugin people might get interested as well and have a look at HipChat.

**Comment by edog1203** [comment]
+1 for easier installation from Jenkins. I don't have the ability to easily build the .hpi.

**Comment by darrinholst** [comment]
Need help with this? Looks like it's just getting the jenkins admins to setup a repo under jenkinsci and adding some config to the pom.

**Comment by pjboudrx** [comment]
Thanks, Darrin! I checked out the wiki page (https://wiki.jenkins-ci.org/display/JENKINS/HipChat+Plugin), and I see it in the json at http://updates.jenkins-ci.org/update-center.json; for some reason my Jenkins instance isn't listing it, but I'l just upload the published hpi.

Thanks again; hope I can return the favor some time soon.

**Comment by darrinholst** [comment]
Yeah, that's weird. I just checked my instance and it's listed as available now. Jenkins 1.477.

**Comment by pjboudrx** [comment]
The problem is certainly with my Jenkins instance not showing me the updated plugin list in the UI; the plugin is clearly published.

Thanks again!
